name: Docker Build and Push

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker image
      run: |
        docker build -t libro-e-library-backend:latest .
        docker build -t libro-e-library-backend:${{ github.sha }} .
    
    - name: Test Docker image
      run: |
        docker run --rm -d -p 8080:80 --name test-container libro-e-library-backend:latest
        sleep 10
        curl -f http://localhost:8080/health || exit 1
        docker stop test-container
